# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Quiz.ui'
#
# Created: Wed Dec 21 20:20:20 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rA = QtGui.QRadioButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rA.sizePolicy().hasHeightForWidth())
        self.rA.setSizePolicy(sizePolicy)
        self.rA.setText("")
        self.rA.setObjectName("rA")
        self.gridLayout.addWidget(self.rA, 0, 0, 1, 1)
        self.rC = QtGui.QRadioButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rC.sizePolicy().hasHeightForWidth())
        self.rC.setSizePolicy(sizePolicy)
        self.rC.setText("")
        self.rC.setObjectName("rC")
        self.gridLayout.addWidget(self.rC, 1, 0, 1, 1)
        self.rD = QtGui.QRadioButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rD.sizePolicy().hasHeightForWidth())
        self.rD.setSizePolicy(sizePolicy)
        self.rD.setText("")
        self.rD.setObjectName("rD")
        self.gridLayout.addWidget(self.rD, 1, 1, 1, 1)
        self.rB = QtGui.QRadioButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rB.sizePolicy().hasHeightForWidth())
        self.rB.setSizePolicy(sizePolicy)
        self.rB.setText("")
        self.rB.setObjectName("rB")
        self.gridLayout.addWidget(self.rB, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lOutput = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lOutput.sizePolicy().hasHeightForWidth())
        self.lOutput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lOutput.setFont(font)
        self.lOutput.setText("")
        self.lOutput.setTextFormat(QtCore.Qt.AutoText)
        self.lOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.lOutput.setObjectName("lOutput")
        self.horizontalLayout.addWidget(self.lOutput)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lRemaining = QtGui.QLabel(Form)
        self.lRemaining.setText("")
        self.lRemaining.setObjectName("lRemaining")
        self.horizontalLayout_2.addWidget(self.lRemaining)
        self.bFinish = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bFinish.sizePolicy().hasHeightForWidth())
        self.bFinish.setSizePolicy(sizePolicy)
        self.bFinish.setObjectName("bFinish")
        self.horizontalLayout_2.addWidget(self.bFinish)
        self.bNew = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bNew.sizePolicy().hasHeightForWidth())
        self.bNew.setSizePolicy(sizePolicy)
        self.bNew.setObjectName("bNew")
        self.horizontalLayout_2.addWidget(self.bNew)
        self.bNext = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bNext.sizePolicy().hasHeightForWidth())
        self.bNext.setSizePolicy(sizePolicy)
        self.bNext.setObjectName("bNext")
        self.horizontalLayout_2.addWidget(self.bNext)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Quiz by Jakob Jungreithmeir", None, QtGui.QApplication.UnicodeUTF8))
        self.bFinish.setText(QtGui.QApplication.translate("Form", "Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.bNew.setText(QtGui.QApplication.translate("Form", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.bNext.setText(QtGui.QApplication.translate("Form", "Next", None, QtGui.QApplication.UnicodeUTF8))

